name: Release Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Generate Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Give permission to executable
        run: chmod +x gradlew

      - name: Generate Release APK
        run: ./gradlew assembleRelease

      - uses: actions/upload-artifact@master
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk